# # ---
# # apiVersion: apps/v1
# # kind: Deployment
# # metadata:
# #   name: devops-app
# #   labels:
# #     app: devops-app
# # spec:
# #   replicas: 1
# #   selector:
# #     matchLabels:
# #       app: devops-app
# #   template:
# #     metadata:
# #       labels:
# #         app: devops-app
# #     spec:
# #       containers:
# #       - name: devops-container
# #         image: 637423542227.dkr.ecr.us-east-1.amazonaws.com/devops-project:latest
# #         ports:
# #         - containerPort: 3000
# # ...
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: devops-app
#   labels:
#     app: devops-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: devops-app
#   template:
#     metadata:
#       labels:
#         app: devops-app
#     spec:
#       containers:
#       - name: devops-container
#         image: 637423542227.dkr.ecr.us-east-1.amazonaws.com/devops-project:latest
#         ports:
#         - containerPort: 3000
# ---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
  namespace: default
  labels:
    app: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-container
        image: 637423542227.dkr.ecr.us-east-1.amazonaws.com/devops-project-2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"     # Minimum memory
            cpu: "100m"         # Minimum CPU
          limits:
            memory: "512Mi"     # Maximum memory (increased!)
            cpu: "500m"         # Maximum CPU (increased!)
---